### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AmA-sud** [deFiss/telegram_channel_duplicator#2]
PS D:\Telegram channel duplicator\telegram_channel_duplicator-main> python main.py
2022-02-10T09:57:56.111749+0400 | INFO - Created by https://github.com/deFiss
Traceback (most recent call last):
  File "D:\Telegram channel duplicator\telegram_channel_duplicator-main\main.py", line 32, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Telegram channel duplicator\telegram_channel_duplicator-main\main.py", line 27, in main
    client = Client()
  File "D:\Telegram channel duplicator\telegram_channel_duplicator-main\telegram_channel_duplicator\client.py", line 16, in __init__
    self.client = TelegramClient(
  File "C:\Users\**\AppData\Roaming\Python\Python39\site-packages\telethon\client\telegrambaseclient.py", line 264, in __init__
    session = SQLiteSession(session)
  File "C:\Users\**\AppData\Roaming\Python\Python39\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
  File "C:\Users\**\AppData\Roaming\Python\Python39\site-packages\telethon\sessions\sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

**Comment by deFiss** [comment]
fixed
