### ISSUE TITLE
run in python 3.7.5 fail

### ISSUE THREAD

**Issue by zhangdc007** [deFiss/telegram_channel_duplicator#9]
run in your read me doc,but fail:
`[root@VM-16-17-centos telegram_channel_duplicator]# python3 main.py 
2023-04-06T03:31:35.743452+0800 | INFO - Created by https://github.com/deFiss
2023-04-06T03:31:35.757310+0800 | INFO - Account authorization
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    loop.run_until_complete(main())
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "main.py", line 29, in main
    await duplicator.start()
  File "/data/telegram/telegram_channel_duplicator/telegram_channel_duplicator/duplicator.py", line 27, in start
    await self.client.start()
  File "/data/telegram/telegram_channel_duplicator/telegram_channel_duplicator/client.py", line 38, in start
    password=self._enter_password,
  File "/usr/local/python3/lib/python3.7/site-packages/telethon/client/auth.py", line 175, in _start
    if ':' in value:
TypeError: argument of type 'int' is not iterable`

**Comment by deFiss** [comment]
fixed by wrapping the phone number in quotes, I'll update the config example
